### ISSUE TITLE
Using Python versions 2.9 and 2.10 getting EOL error

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-vsphere#127]
When upgrading to version 2.9 and 2.10 I am getting this error when running in a python 3.8 environment. Downgrading to 2.8 allows it to work again.

```
/lib/python3.8/site-packages/pulumi_vsphere/_inputs.py", line 1161
        warnings.warn("
                      ^
    SyntaxError: EOL while scanning string literal
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

**Comment by justinvp** [comment]
We need to handle escaping newlines.

https://github.com/pulumi/pulumi-vsphere/blob/408395dd12b2b592f5275781067604657526e652/sdk/python/pulumi_vsphere/_inputs.py#L1160-L1182

**Comment by jongoneok** [comment]
You should be able to get through that by editing the _inputs.py file to use triple quotes on that word-wrapped string.

`if name is not None:
            warnings.warn("""
            The name attribute for virtual disks will be removed in favor of \"label\" in
            future releases. To transition existing disks, rename the \"name\" attribute to
            \"label\". When doing so, ensure the value of the attribute stays the same.

            Note that \"label\" does not control the name of a VMDK and does not need to bear
            the name of one on new disks or virtual machines. For more information, see the
            documentation for the label attribute at:

            https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#label
            """, DeprecationWarning)
            pulumi.log.warn("""
            name is deprecated:
            The name attribute for virtual disks will be removed in favor of \"label\" in
            future releases. To transition existing disks, rename the \"name\" attribute to
            \"label\". When doing so, ensure the value of the attribute stays the same.

            Note that \"label\" does not control the name of a VMDK and does not need to bear
            the name of one on new disks or virtual machines. For more information, see the
            documentation for the label attribute at:

            https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#label
            """)
`

**Comment by komalali** [comment]
We'll do a patch release in the morning with this fixed.
