### ISSUE TITLE
pulumi up fails because of a multiline string in _inputs.py

### ISSUE THREAD

**Issue by omniproc** [pulumi/pulumi-vsphere#143]
A bug in `_inputs.py` - probably caused by the `tfgen` code generation - currently is causing pulumi-vsphere not to work. 

https://github.com/pulumi/pulumi-vsphere/blob/69145724f1fb0aa91b229cc0120a0824b8807d37/sdk/python/pulumi_vsphere/_inputs.py#L969-L990

Using the vSphere provider will fail with

> SyntaxError: EOL while scanning string literal
>     error: an unhandled error occurred: Program exited with non-zero exit code: 1

This can easily be fixed by wrapping any string that contains a EOL char in tripple quotes. I'd submit a PR but since this is generated by  `tfgen` it probably makes more sense to fix it in there, since this seems to be a generic issue with the python code generation.

**Comment by stack72** [comment]
Hi @omniproc 

Apologies you are getting this error - I will get this fixed up and a new version shipped ASAP!

Paul
