### ISSUE TITLE
Please add example for Python

### ISSUE THREAD

**Issue by patsevanton** [pulumi/pulumi-vsphere#167]
Hello! Thanks for pulumi-vsphere provider.
Please add example for Python.
Thanks!

**Comment by leezen** [comment]
@patsevanton Do you mind clarifying what kind of examples you're looking for? In our documentation, we have example snippets of how to use common resource types. For example, https://www.pulumi.com/docs/reference/pkg/vsphere/host/ (choose "Python" in the language selector) has a Python example on using this resource.

**Comment by declum** [comment]
Is there any example on how to Create VirtualMachine from ContentLibrary?

**Comment by iwahbe** [comment]
https://github.com/pulumi/pulumi-vsphere/pull/597 should restore a bunch of examples.

@patsevanton If you are looking for any additional examples, can you open a more specific issue? Thanks!
