### ISSUE TITLE
FixedIps/Static ip - Pulumi-vSphere Virtualmachine creation

### ISSUE THREAD

**Issue by yomofo2s** [pulumi/pulumi-vsphere#176]
I have never came accross an example of a vsphere virtualmachine static ip address assignment. I am working on creating a virtualmachine by cloning a template and assigning a static ip address instead of a dynamic IP.

I would like to see a solution example like this. -->

```ts
 const port1 = new vsphere.networkId("network", {
        fixedIps: [{
            ipv4Address:"192.168.218.318",
            ipv4Netmask: "24"
        }]
    },
      ipv4Gateway : "192.168.60.1"
    dnssuffixlists : ["example.com",
    }];
```

All i could found on your example is something related to this using typescript

https://github.com/pulumi/pulumi-vsphere/blob/master/examples/webserver/index.ts
P:S my vsphere environment does not support a dynamic ip address as shown below, so therefore i need to assign a static ip.

![image](https://user-images.githubusercontent.com/44329653/124854579-d326cd00-dfa7-11eb-8da8-a3c42aa3048a.png)

many thanks

**Comment by lukehoban** [comment]
There is not a full example of this in the docs currently unfortunately - but I believe you ultimately need to use https://www.pulumi.com/docs/reference/pkg/vsphere/virtualmachine/#ipv4address_nodejs, which is exposed via the https://www.pulumi.com/docs/reference/pkg/vsphere/virtualmachine/#clone_nodejs property and it's `customize` and `networkInterfaces` properties.

**Comment by lukehoban** [comment]
Opened https://github.com/pulumi/pulumi-vsphere/issues/179 on the missing docs content.  Will close this one out and track the broader missing docs issue there.

**Comment by yomofo2s** [comment]
Seems no headway with the synthax. Is there anyway that i can declare this properly`? I just want to add a static IP to my vSphere.

const port1 = new vsphere.networkId("ntz", {
        fixedIps: [{
            ipv4Address:"192.168.10.8",
            ipv4Netmask: "24"
        }]
    },
    
    )
    ipv4Gateway : "192.168.10.1"
    dnssuffixlists : ["example.de",
    }];
