### ISSUE TITLE
VirtualMachine Disk

### ISSUE THREAD

**Issue by yomofo2s** [pulumi/pulumi-vsphere#177]
I am wondering if there is an enablement for vsphere virtualmachine additional disk configuration. I am working on creating a virtualmachine by cloning a template and assigning an additional 3 disks.

I would like to see a solution example like this for 3 additional disks. -->

```ts
disks: [{
        label: "disk0",
        size: template.then(t => t.disks[0].size),
        eagerlyScrub: template.then(t => t.disks[0].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[0].thinProvisioned),
    }],
```

All i could found on your example is something related to a single disk above using typescript.

https://github.com/pulumi/pulumi-vsphere/blob/master/examples/webserver/index.ts

P:S my vsphere clone machinedoes not support a single disk so therefore i need to assign additional 3disk.

![image](https://user-images.githubusercontent.com/44329653/124854579-d326cd00-dfa7-11eb-8da8-a3c42aa3048a.png)

Would there be possible to have something like this:
_disks: [{
        label: "disk1",
        size: template.then(t => t.disks[1].size),
        eagerlyScrub: template.then(t => t.disks[1].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[1].thinProvisioned),
    }],

    disks: [{
        label: "disk2",
        size: template.then(t => t.disks[2].size),
        eagerlyScrub: template.then(t => t.disks[2].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[2].thinProvisioned),
    }],

    disks: [{
        label: "disk3",
        size: template.then(t => t.disks[3].size),
        eagerlyScrub: template.then(t => t.disks[3].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[3].thinProvisioned),
    }],_
many thanks

**Comment by lukehoban** [comment]
You should be able to do this as:

```ts
disks: [{
    label: "disk2",
    size: template.then(t => t.disks[2].size),
    eagerlyScrub: template.then(t => t.disks[2].eagerlyScrub),
    thinProvisioned: template.then(t => t.disks[2].thinProvisioned),
}, {
    label: "disk3",
    size: template.then(t => t.disks[3].size),
    eagerlyScrub: template.then(t => t.disks[3].eagerlyScrub),
    thinProvisioned: template.then(t => t.disks[3].thinProvisioned),
}]
```

Note that https://github.com/pulumi/pulumi-vsphere/issues/179 is tracking improving the docs, and ensuring that more of the content from [upstream](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#disk-options) is available in the Pulumi docs.

**Comment by yomofo2s** [comment]
Hi @lukehoban thanks for your feedback. I adjusted the configuration however, i received the following error.
![image](https://user-images.githubusercontent.com/44329653/125875030-62d4c929-1b69-4e27-b973-8a0a3d5cbbc8.png)

Here is my disk code:

disks: [{
        label: "disk0",
        size: template.then(t => t.disks[0].size),
        eagerlyScrub: template.then(t => t.disks[0].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[0].thinProvisioned),
    }, {

        label: "disk1",
        size: template.then(t => t.disks[1].size),
        eagerlyScrub: template.then(t => t.disks[1].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[1].thinProvisioned),
    }, {

        label: "disk2",
        size: template.then(t => t.disks[2].size),
        eagerlyScrub: template.then(t => t.disks[2].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[2].thinProvisioned),
    }, {

        label: "disk3",
        size: template.then(t => t.disks[3].size),
        eagerlyScrub: template.then(t => t.disks[3].eagerlyScrub),
        thinProvisioned: template.then(t => t.disks[3].thinProvisioned),
    }],

**Comment by lukehoban** [comment]
See the docs on `unit_number` at https://www.pulumi.com/docs/reference/pkg/vsphere/virtualmachine/#unit_number_python.

> The disk number on the storage bus. The maximum value for this setting is the value of the controller count times the controller capacity (15 for SCSI, 30 for SATA, and 2 for IDE). **The default is 0, for which one disk must be set to. Thanks Duplicate unit numbers are not allowed.**
