### ISSUE TITLE
API documentation is not yet published

### ISSUE THREAD

**Issue by retr0h** [pulumi/pulumi-vsphere#22]
I see the documentation states the API docs are not yet published.  Is this module not yet complete?  Any idea when it will be considered ready for consumption?

Thanks -
John

**Comment by lukehoban** [comment]
Fixed this in the README.  Docs are here:

* NodeJS: https://pulumi.io/reference/pkg/nodejs/@pulumi/vsphere/index.html
* Python: Coming soon!
* Go: https://godoc.org/github.com/pulumi/pulumi-vsphere/sdk/go/vsphere
