### ISSUE TITLE
stray output in python doc

### ISSUE THREAD

**Issue by ericrudder** [pulumi/pulumi-vsphere#350]
i noticed some extra characters while working on a sample.  

note the /* strays in the https://pulumi.io/reference/pkg/python/pulumi_vsphere; according to @swgillespie, this is unique enough for a new issue.

**Comment by mjeffryes** [comment]
We strip these trailing '*' characters in docs now. That does mean that the footnote is not included, however, this footnote is actually irrelevant to the majority of the parameters it is added to, so I think this is strictly better.
