### ISSUE TITLE
Update DistributedVirtualSwitch resource to support vSphere 7

### ISSUE THREAD

**Issue by nvpnathan** [pulumi/pulumi-vsphere#74]
Hi all,
Can we update the DVS resource support version 7.0.0 that ships with vSphere 7?

Diagnostics:
  vsphere:index:DistributedVirtualSwitch (pl-comp-dvs):
    error: vsphere:index/distributedVirtualSwitch:DistributedVirtualSwitch resource 'pl-comp-dvs' has a problem: expected version to be one of [5.0.0 5.1.0 5.5.0 6.0.0 6.5.0], got 7.0.0

**Comment by nvpnathan** [comment]
It's interesting if you don't specify a version it defaults to 7.0.0. I have some clusters that require VDS version 6.5.0 and others require 7.0.0. It will not accept an empty or null value.

**Comment by leezen** [comment]
Thanks for reporting this. I believe this is an issue upstream: https://github.com/terraform-providers/terraform-provider-vsphere/blob/534931a5deb3be12c7217b6794781299fdce28cb/vsphere/distributed_virtual_switch_helper.go#L16

@stack72 does that look right to you?

**Comment by mikhailshilkov** [comment]
The version has been added upstream: https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/distributed_virtual_switch_helper.go#L26

It's also available in Pulumi.
