### ISSUE TITLE
No way to catch error/exception 

### ISSUE THREAD

**Issue by nhi-vanye** [pulumi/pulumi-vsphere#94]
Using the same example in #92 - but using a Ubuntu-14 template (as opposed to Ubuntu-20) getting an error that I can't trap

However the VMs are created - but there's no way to capture the error/exception and handle the IP address lookup myself.

```
Do you want to perform this update? yes
Updating (testing):
     Type                             Name              Status                  Info
     pulumi:pulumi:Stack              XXXX-testing  **failed**              1 error
 ~   ├─ vsphere:index:VirtualMachine  rmo-su-1          **updating failed**     [diff: ~vapp];
 ~   ├─ vsphere:index:VirtualMachine  rmo-cc-1          **updating failed**     [diff: ~vapp];
 
Diagnostics:
  pulumi:pulumi:Stack (labminds-testing):
    error: update failed

  vsphere:index:VirtualMachine (rmo-su-1):
    error: 1 error occurred:
    	* updating urn:pulumi:testing::XXXX::vsphere:index/virtualMachine:VirtualMachine::rmo-su-1: timeout waiting for an available IP address
```

**Comment by leezen** [comment]
If this is due to a `get` then I think this is the same as https://github.com/pulumi/pulumi/issues/3364

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)
